version: "2.1"
orbs:
  slack: circleci/slack@4.1

executors:
  sapi-executor:
    docker:
      - image: "cimg/node:16.16.0"
    resource_class: medium

aliases:
  - &setup
    steps:
      - checkout
      - run: sudo apt-get update  
      - run:
          name: Install deps
          command: npm install
      - run:
          name: Run ci
          command: npm ci
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish package
          command: npm publish --tag test
      - slack/notify:
          channel: circleci-backend-deploys
          event: fail
          template: basic_fail_1
      - slack/notify:
          channel: circleci-backend-deploys
          event: pass
          template: success_tagged_deploy_1

jobs:
  build-and-test:
    executor: sapi-executor
    <<: *setup

workflows:
  build-and-test-api:
    jobs:
      - build-and-test:
          context: 
            - translate-extension-languages
            - slack-notifications
